controller_manager:
  ros__parameters:
    update_rate: 50
    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["front left wheel", "back left wheel"]
    right_wheel_names: ["front right wheel", "back right wheel"]
    wheel_separation: 0.4
    wheel_radius: 0.11
    wheels_per_side: 1
    enable_odom_tf: true
    use_stamped_vel: false
    base_frame_id: "base_link"